# Generated by Django 3.0.2 on 2020-02-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IntentSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_intents.IntentModel')),
            ],
        ),
    ]
