# Generated by Django 3.0.3 on 2020-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentslot',
            old_name='intent',
            new_name='intent_label',
        ),
        migrations.AddField(
            model_name='intentslot',
            name='color_hex',
            field=models.CharField(default='#4b4b4b', max_length=9),
        ),
    ]
