# Generated by Django 3.0.3 on 2020-02-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0002_auto_20200211_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentinstance',
            old_name='intent_slots',
            new_name='seq_in',
        ),
        migrations.RenameField(
            model_name='intentinstance',
            old_name='intent_text',
            new_name='seq_out',
        ),
    ]
