# Generated by Django 3.0.3 on 2020-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0004_auto_20200206_1041'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='intentmodel',
            constraint=models.UniqueConstraint(fields=('intent_label',), name='constraint'),
        ),
    ]
