# Generated by Django 3.0.3 on 2020-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0005_auto_20200214_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentinstance',
            name='augmentation',
            field=models.BooleanField(default=False),
        ),
    ]
