# Generated by Django 3.0.3 on 2020-05-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0006_intentinstance_augmentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentinstance',
            old_name='augmentation',
            new_name='is_augmentation',
        ),
    ]
