# Generated by Django 3.0.6 on 2020-05-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0007_auto_20200512_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intentinstance',
            old_name='is_synthetic',
            new_name='is_synthetic',
        ),
    ]
