# Generated by Django 3.0.6 on 2020-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0008_auto_20200515_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentinstance',
            name='is_synthetic',
        ),
        migrations.AddField(
            model_name='intentinstance',
            name='excempt_shuffle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentinstance',
            name='excempt_stemmify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentinstance',
            name='excempt_synonym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intentinstance',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
    ]
