# Generated by Django 3.0.6 on 2020-05-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0009_auto_20200515_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intentinstance',
            name='excempt_shuffle',
        ),
        migrations.RemoveField(
            model_name='intentinstance',
            name='excempt_stemmify',
        ),
        migrations.RemoveField(
            model_name='intentinstance',
            name='excempt_synonym',
        ),
    ]
