# Generated by Django 3.0.6 on 2020-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0011_auto_20200515_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentslot',
            name='unique_values_only',
            field=models.BooleanField(default=False),
        ),
    ]
