# Generated by Django 3.0.6 on 2020-07-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0012_intentslot_unique_values_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentCCIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore_intent', models.CharField(max_length=50)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit_intents.IntentCategory')),
            ],
        ),
    ]
