# Generated by Django 3.0.6 on 2020-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_intents', '0013_intentccignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentslot',
            name='dont_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='intentccignore',
            unique_together={('intent', 'ignore_intent')},
        ),
    ]
